### ISSUE TITLE
Not understanding how it work

### ISSUE THREAD

**Issue by microSoftware** [sergiotapia/torrentinim#13]
I ran torrentinim with ./torrentinim on macos in the terminal. And it crawl all the torrent site endlessly 

![Screen Shot 2021-07-24 at 18 31 17](https://user-images.githubusercontent.com/3915272/126875028-9cf29bce-5a81-477f-a8f8-776b19138c4b.png)

<img width="1380" alt="Screen Shot 2021-07-24 at 18 31 07" src="https://user-images.githubusercontent.com/3915272/126875016-aed6f806-34b5-437b-a090-d759f58f3a7d.png">

I thought it was a torrent search engine which request all the torrent site simultaneously and display the result.

Am i missing something? Why would anyone want to download the whole torrent websites when they can just request only the thing they want?

**Comment by sergiotapia** [comment]
Hey! This project is meant to stay running in the background somewhere on your PC. You would then use the API to search for torrents you are interested in, instead of going to all these other destinations one by one to find something you like.

Sonarr and Radarr support is coming at some point (see open PRs) so you can just point them to torrentinim and have great results.
